name: shareme
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter


  # UI
  bootstrap_icons: ^1.5.0

  lucide_icons: ^0.16.13

  flutter_svg: ^0.23.0+1
  google_fonts: ^2.1.0
  intro_slider: ^2.4.3
  responsive_framework: ^0.1.5

  qr_flutter: ^4.0.0
  flutter_markdown: ^0.6.8

  # todo linux support
  wakelock: ^0.5.6

  widget_to_image:
    git: https://github.com/marchellodev/widget_to_image.git


  # UTILS
  http: ^0.13.4

  url_launcher: ^6.0.12
  device_apps: ^2.1.1

#  hive: ^2.0.4
  hive_flutter: ^1.1.0


  intl: ^0.17.0
  collection: ^1.15.0

  # todo implement
  receive_sharing_intent: ^1.4.5



  # Android and IOS
  file_picker: ^4.2.0


  # Desktop
  file_selector: ^0.8.2+1
  file_selector_windows: ^0.0.2+1
  file_selector_linux: ^0.0.2+1
  file_selector_macos: ^0.0.4+1


  # ARCHITECTURE
  provider: ^6.0.1

  # ANALYTICS
  ackee_dart: ^0.0.2




dev_dependencies:
  build_runner: ^2.1.4
  hive_generator: ^1.1.1

  lint: ^1.7.2

  flutter_native_splash: ^1.3.1
  change_app_package_name: ^1.0.0
  flutter_lints: ^1.0.4




flutter_native_splash:
  # [Colors.deepPurple.shade400]
  color: "#7E57C2"
  web: false

flutter:
  generate: true
  uses-material-design: false

  assets:
    - assets/
    - assets/slides/
    - assets/flags/
    - google_fonts/Andika/
    - google_fonts/Comfortaa/
    - google_fonts/JetBrains/
    - google_fonts/Poppins/